#ifndef INCLUDE_H
#define INCLUDE_H
// 此文件用于包含所有头文件
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "strcutures/Task.h"
#include "strcutures/TaskDay.h"
#include "strcutures/TaskMonth.h"
#include "strcutures/TaskYear.h"
#include "strcutures/setting.h"
#include "display/show_data.h"
#include "display/color.h"
#include "tools/tools.h"
#include "tools/MONTH.h"
#include "database/load_data.h"
#include "database/save_data.h"
#include "database/delete_data.h"
#include "database/modify_data.h"
#include "database/add_data.h"
#include "database/filePath.h"
#include "database/save_setting.h"
#include "execute/find.h"
#include "execute/delete.h"
#include "execute/modify.h"
#include "execute/add.h"
#include "display/help.h"
#include "execute/done.h"
#include "execute/undo.h"
#include "execute/set_setting.h"

#endif