#ifndef INCLUDE_H
#define INCLUDE_H
// 此文件用于包含所有头文件
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <time.h>
#include "strcutures/task_day/Task.h"
#include "strcutures/task_day/TaskDay.h"
#include "strcutures/task_day/TaskMonth.h"
#include "strcutures/task_day/TaskYear.h"
#include "strcutures/task_week/Week_Task.h"
#include "strcutures/task_Week/Week_Year_Task.h"
#include "strcutures/task_month/Month_Task.h"
#include "strcutures/task_month/Month_Year_Task.h"
#include "strcutures/task_year/Year_Task.h"
#include "setting/setting.h"
#include "display/show_data.h"
#include "display/color.h"
#include "tools/tools.h"
#include "tools/MONTH.h"
#include "database/load_data.h"
#include "database/save_data.h"
#include "database/delete_data.h"
#include "database/modify_data.h"
#include "database/add_data.h"
#include "database/filePath.h"
#include "database/save_setting.h"
#include "execute/find.h"
#include "execute/delete.h"
#include "execute/modify.h"
#include "execute/add.h"
#include "display/help.h"
#include "execute/done.h"
#include "execute/undo.h"
#include "execute/set_setting.h"
#include "log/log.h"
#include "lexer/date.h"
#endif